version: '3.7'
services:
  mysql_db_container:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  adminer_container:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8081:8080
    links:
      - mysql_db_container

volumes:
  mysql_db_data_container:
